[features]
seeds = false
skip-lint = false
[programs.localnet]
staking_contract = "CeJBBeP56NLJkGSoDzm6CQxJ2NXSo7jeEsXrhkZ3Mr55"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/rajeeb/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
